---
driver:
  name: vagrant
driver_config:
  require_chef_omnibus: 12.16.42

provisioner:
  name: chef_zero
  roles_path: 'test/integration/roles'
  data_bags_path: 'test/integration/data_bags'
  encrypted_data_bag_secret_key_path: '../../secrets/encrypted_data_bag_secret'
  environments_path: 'test/integration/environments'
  client_rb:
    environment: 'test_hms'

verifier:
  sudo: true
  name: inspec

platforms:
  - name: centos-7.3
  - name: centos-7.4

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "33.33.33.11"}]
    run_list:
      - role[default]
    attributes:
